/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fun.fifu;

import fun.fifu.huohua.App;
import fun.fifu.huohua.ConfigPojo;
import org.junit.Test;

import javax.swing.plaf.IconUIResource;

public class AppTest {
    @Test
    public void testAppHasAGreeting() throws Exception {
        System.out.println("Hello Test");
        /*
        Class aClass = Class.forName("fun.fifu.huohua.App");
        Method main = aClass.getMethod("main", String[].class);
        main.invoke(null, (Object) new String[]{});
        */
        /*
        Terminal terminal = TerminalBuilder.builder()
                .system(true)
                .build();

        LineReader lineReader = LineReaderBuilder.builder()
                .terminal(terminal)
                .build();

        String prompt = "fog>";
        while (true) {
            String line;
            try {
                line = lineReader.readLine(prompt);
                switch (line) {
                    case "awa":
                        System.out.println("啊伟大伟大");
                        break;
                    case "owo":
                        System.out.println("小白最帅");
                        break;
                    default:
                        System.out.println(line);
                        break;
                }
            } catch (UserInterruptException e) {
                // Do nothing
            } catch (EndOfFileException e) {
                System.out.println("\nBye.");
                return;
            }
        }
        */

//
//        QQMan q = new QQMan("config.yml");
//        Qa qa = new Qa();
//        qa.tryAdd("问钟小白答最帅");
//        System.out.println(qa.qa("钟小白"));

        App.captureScreen2("小白","qwq.png");

    }

    @Test
    public void configTest(){
        ConfigPojo configPojo = new ConfigPojo().readConfig();
        System.out.println(configPojo);
        configPojo.saveData();
    }
}
